### ISSUE TITLE
Location object needs a lattitude and longitude properties

### ISSUE THREAD

**Issue by shashikantj** [Codigami/face4j#14]
E.g. consider the following location Mulgrave, Victoria, Australia

https://graph.facebook.com/107405229297329

facebook provides with lat and lon

**Comment by nischal** [comment]
Cool, I'll add them to the location object

**Comment by nischal** [comment]
Added latitude and longitude to location object. You can download the jar here - https://github.com/downloads/nischal/face4j/dist-1.5.11.zip
