### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by vilhalba** [Codigami/face4j#17]
How i put proxy in facebookfactory?

**Comment by nischal** [comment]
I will have to look into this. You want this for Google Appengine?

**Comment by vilhalba** [comment]
No, my project is JSF2 application with Apache Tomcat.

**Comment by nischal** [comment]
Cool. I'm checking this right now. Will update soon.

**Comment by nischal** [comment]
Can you download this http://www.4shared.com/zip/wFnxWHni/face4j.html  unzip it and include all the jars inside 'dependency' as well as the face4j jar. Include the face4j.properties file in your classpath after entering the proxy config in it. Let me know if it works.

**Comment by vilhalba** [comment]
I tried to put face4j.properties in to src of my application, but doenst worked. My proxy dont needs  the username and password.Am  I wrong?

**Comment by nischal** [comment]
Try this - http://www.4shared.com/zip/F_81AoIs/face4j_2.html  I will try to set up a proxy on my end to test this better in case this too does not work. In this file, just extract the face4j.jar file and the face4j.properties file. The face4j.properties file should be in your classpath

**Comment by vilhalba** [comment]
I change some thinks, and works fine. Thank you. Nice job.

**Comment by nischal** [comment]
You mean the latest jar and face4j.properties works for you?

**Comment by vilhalba** [comment]
Yes, the latest jar with modifications in my app. Thank you.

**Comment by nischal** [comment]
The latest version of face4j now supports proxy.
